config/routes.rb
EjemploAutenticacion::Application.routes.draw do
  resources :authentications

  devise_for :users,  path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  root 'default#index'

  get '/entrar', to: 'authentications#index', as: 'entrar'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user

	def index

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

    has_many :authentications, :dependent => :delete_all

    def apply_omniauth(omniauth)
    	authentications.new(:provider => omniauth['provider'], :uid => omniauth['uid'], :token => omniauth['credentials'].token, :token_secret => omniauth['credentials'].secret)
  	end

  	def password_required?
    	(authentications.empty? || !password.blank?) && super 
    end
  
  	def update_with_password(params, *options)
    	if encrypted_password.blank?
      		update_attributes(params, *options)
    	else
      		super
    	end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	
	def index
	end

	def destroy
 		@authentication = Authentication.find(params[:id])
 		@authentication.destroy
 		redirect_to authentications_url, :notice => "Autenticación destruida exitosamente."
   	end

	def all
		omniauth = request.env["omniauth.auth"]
     	authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])

     	if authentication
       		flash[:notice] = "Usuario logueado con éxito."
       		sign_in_and_redirect User.find(authentication.user_id)
     	elsif current_user
       		token = omniauth['credentials'].token

       		if omniauth['provider'] == "twitter"
       			token_secret = omniauth['credentials'].secret
       		else
       			token_secret = ""
       		end		

   			current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'], :token => token, :token_secret => token_secret)
   			
   			flash[:notice] = "Autenticación exitosa."
       		sign_in_and_redirect current_user
     	else
       		user = User.new 

       		user.email = omniauth['extra']['raw_info'].email if omniauth['provider'] == 'facebook'

       		user.apply_omniauth(omniauth)

	       	if user.save
	     		flash[:notice] = "Logueado con éxito."
	         	sign_in_and_redirect User.find(user.id)             
	       	else
	     		session[:omniauth] = omniauth.except('extra')
	     		redirect_to new_user_registration_path
	       	end
	 	end 
   	end
	alias_method :twitter, :all
	alias_method :facebook, :all
 	
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def create
    	super
    	session[:omniauth] = nil unless @user.new_record?
  	end
  
  	def build_resource(*args)
  		super
      	if session[:omniauth]
        	@user.apply_omniauth(session[:omniauth])
        	@user.valid?
      	end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authentications/index.html.erb
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
 	<%= link_to 'Editar perfil', edit_user_registration_path %> |
 	<%= link_to 'Autenticaciones', authentications_path %> |
 	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Crear cuenta", new_user_registration_path %> |
	<%= link_to "Iniciar sesión", new_user_session_path %>
	<li><%= link_to "Conectar con Twitter", user_omniauth_authorize_path(:twitter) %></li>
	<li><%= link_to "Conectar con Facebook", user_omniauth_authorize_path(:facebook) %></li>
<% end %>

app/views/default/index.html.erb
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
 	<%= link_to 'Editar perfil', edit_user_registration_path %> |
 	<%= link_to 'Autenticaciones', authentications_path %> |
 	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
	¿Aún no inicias sesión? Haz <%= link_to 'click aquí', entrar_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EjemploAutenticacion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>